final periodic job upload script

diff --git a/report-portal-upload/cron_job.yml b/report-portal-upload/cron_job.yml
--- a/report-portal-upload/cron_job.yml
+++ b/report-portal-upload/cron_job.yml
@@ -50,58 +50,66 @@ spec:
               value: artifacts/console-aws/e2e-test/artifacts/gui_test_screenshots/junit_cypress*.xml
 
             command:
-              - "/bin/sh"
-              - "-c"
-              - |
-                failed=false
-                latest_build_ID=$(curl "$JOB_URL/latest-build.txt")
-                echo "latest build id : $latest_build_ID"
+                - /bin/sh
+                - '-c'
+                - >
+                  failed=false
+                  latest_build_ID=$(curl "$JOB_URL/latest-build.txt")
+                  echo "latest build id : $latest_build_ID"
 
-                #Check if the timestamp of the last build is not older than 12 hours.
-                timestamp=$(curl -s "$JOB_URL/$latest_build_ID/started.json" | grep -oP '"timestamp":\K\d+')
-                twelve_hours_ago=$(date -u -d '12 hours ago' +%s)
+                  #Check if the timestamp of the last build is not older than 12 hours.
+                  timestamp=$(curl -s "$JOB_URL/$latest_build_ID/started.json" | grep -oP '"timestamp":\K\d+')
+                  twelve_hours_ago=$(date -u -d '12 hours ago' +%s)
 
-                if [ "$timestamp" -le "$twelve_hours_ago" ]; then
-                  echo "Skipping : Latest build is older than 12 hours"
-                  exit 0
-                fi
+                  if [ "$timestamp" -le "$twelve_hours_ago" ]; then
+                    echo "Skipping : Latest build is older than 12 hours"
+                    exit 0
+                  fi
 
-                cd /tmp
-                mkdir ./artifacts
+                  cd /tmp
+                  mkdir ./artifacts
 
-                export CLOUDSDK_CONFIG=/tmp
-                gsutil -m -o "GSUtil:state_dir=/tmp" cp -r "$OPENSHIFTCI_JOB_GS/$latest_build_ID/$OPENSHIFTCI_JOB_ARTIFACTS_PATH" artifacts
-                
-                gsutil -m -o "GSUtil:state_dir=/tmp" cp -r "$OPENSHIFTCI_JOB_GS/$latest_build_ID/artifacts/junit_operator.xml" artifacts
 
-                if [ $ -eq 0 ]; then
+                  export CLOUDSDK_CONFIG=/tmp
+
+                  if (gsutil -m -o "GSUtil:state_dir=/tmp" cp -r
+                  "$OPENSHIFTCI_JOB_GS/$latest_build_ID/$OPENSHIFTCI_JOB_ARTIFACTS_PATH"
+                  artifacts); then
+                    echo "Successfully downloaded artifacts!"
+                  else
+                    echo "Failed to download/locate artifacts!"
+                    curl -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" -d "text=:red-siren: Periodic Job : Failed to download/locate artifacts" -d "channel=${SLACK_CHANNEL_ID}" -X POST https://slack.com/api/chat.postMessage
+                  fi
+
+                  gsutil -m -o "GSUtil:state_dir=/tmp" cp -r
+                  "$OPENSHIFTCI_JOB_GS/$latest_build_ID/artifacts/junit_operator.xml"
+                  artifacts
+
+
                   curl -o rp_xml_update_and_zip.py $PY_XML_UPDATE_SCRIPT
 
+
                   zip_file=$(python3 rp_xml_update_and_zip.py /tmp/artifacts)
+
+                  echo "Zip file location"
                   echo "$zip_file"
+
 
                   response=$(curl -k -X POST \
                     -H "Authorization: Bearer ${REPORTPORTAL_TOKEN}" \
                     -H "Content-Type: multipart/form-data" \
-                    -F "file=@${zip_file}" \
-                    $HAC_DEV_REPORT_IMPORT_URL)
-                  
+                    -F "file=@artifacts/periodic-job.zip" \
+                    $DEV_CONSOLE_REPORT_IMPORT_URL)
+
                   if echo "$response" | grep -q "successfully imported"; then
                       echo "Success: $response"
                   else
                       echo "Error: $response"
-                      upload_failed=true
+                      failed=true
                   fi
-                fi
 
-                if [ "$upload_failed" = true ]; then
-                  echo "Upload failed"
-                  #curl -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" -d "text=:red-siren: Periodic Job : Failed to upload report on report portal" -d "channel=${SLACK_CHANNEL_ID}" -X POST https://slack.com/api/chat.postMessage
-                  exit 1
-                fi
 
-                if [ "$failed" = true ]; then
-                  echo "Upload failed"
-                  #curl -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" -d "text=:red-siren: Periodic Job : Failed to upload report on report portal" -d "channel=${SLACK_CHANNEL_ID}" -X POST https://slack.com/api/chat.postMessage
-                  exit 1
-                fi
+                  if [ "$failed" = true ]; then
+                    curl -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" -d "text=:red-siren: Periodic Job : Failed to upload report on report portal" -d "channel=${SLACK_CHANNEL_ID}" -X POST https://slack.com/api/chat.postMessage
+                    exit 1
+                  fi
